//+------------------------------------------------------------------+
//| donchian_breakout_EURUSD_H1.mq4
//| Generated by the Agentic Trading Firm - Strategy Lab
//| 2026-08-13 04:22 UTC
//|
//| Strategy   : donchian_breakout
//| Symbol/TF  : EURUSD H1
//| Parameters : {"channel": 15, "atr_mult": 1.5, "rr": 4, "buffer_atr": 0}
//|
//| BACKTEST (in-sample, spread-adjusted)
//|   trades 59 | win 38.98% | PF 2.5
//|   expectancy 0.9259R | maxDD 3.036R
//|   sharpe 2.934 | robustness score 1.3935
//| WALK-FORWARD: {"folds": 3, "oos_total_r": 15.196, "oos_trades": 40, "oos_expectancy_r": 0.3799, "params_per_fold": [{"channel": 10, "atr_mult": 1.5, "rr": 2.5, "buf
//|
//| Past performance does not predict future results. Test on demo first.
//+------------------------------------------------------------------+
#property copyright "Agentic Trading Firm"
#property version   "1.00"
#property strict

input double RiskPercent   = 0.75;    // % equity risked per trade
input double ATRMultiplier = 1.5;   // stop distance
input double RewardRatio   = 4.0;   // target = R x stop
input int    ATRPeriod     = 14;
input int    MagicNumber   = 617002;
input int    Slippage      = 20;
input int    MaxPositions  = 1;
input bool   TradeOnNewBarOnly = true;

datetime lastBar = 0;

int OnInit()
  {
   Print("donchian_breakout_EURUSD_H1 initialised. Risk ", RiskPercent, "% | ATRx", ATRMultiplier, " | RR ", RewardRatio);
   return INIT_SUCCEEDED;
  }

int CountPositions()
  {
   int c = 0;
   for(int i = OrdersTotal() - 1; i >= 0; i--)
     {
      if(!OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) continue;
      if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber
         && (OrderType() == OP_BUY || OrderType() == OP_SELL)) c++;
     }
   return c;
  }

double LotsForRisk(double stopDistance)
  {
   double eq   = AccountEquity();
   double risk = eq * RiskPercent / 100.0;
   double tv   = MarketInfo(Symbol(), MODE_TICKVALUE);
   double ts   = MarketInfo(Symbol(), MODE_TICKSIZE);
   if(ts <= 0 || tv <= 0 || stopDistance <= 0) return 0.0;
   double lossPerLot = stopDistance / ts * tv;
   if(lossPerLot <= 0) return 0.0;
   double lots = risk / lossPerLot;
   double step = MarketInfo(Symbol(), MODE_LOTSTEP);
   double vmin = MarketInfo(Symbol(), MODE_MINLOT);
   double vmax = MarketInfo(Symbol(), MODE_MAXLOT);
   if(step > 0) lots = MathFloor(lots / step) * step;
   if(lots < vmin) return 0.0;
   return MathMin(lots, vmax);
  }

void OnTick()
  {
   if(TradeOnNewBarOnly)
     {
      if(Time[0] == lastBar) return;
      lastBar = Time[0];
     }
   if(CountPositions() >= MaxPositions) return;

   double atr = iATR(NULL, 0, ATRPeriod, 1);
   if(atr <= 0) return;
   double price = Close[1];
   bool buy = false, sell = false;

   double hh = 0, ll = 0;
   hh = High[iHighest(NULL,0,MODE_HIGH,15,2)]; ll = Low[iLowest(NULL,0,MODE_LOW,15,2)];
   double buf = atr * 0.0;
   buy  = price > hh + buf;
   sell = price < ll - buf;
   if(!buy && !sell) return;

   double stopDist = atr * ATRMultiplier;
   double lots = LotsForRisk(stopDist);
   if(lots <= 0) return;

   int digits = (int)MarketInfo(Symbol(), MODE_DIGITS);
   double stopLvl = MarketInfo(Symbol(), MODE_STOPLEVEL) * Point;
   if(stopDist < stopLvl) stopDist = stopLvl;

   if(buy)
     {
      double sl = NormalizeDouble(Ask - stopDist, digits);
      double tp = NormalizeDouble(Ask + stopDist * RewardRatio, digits);
      int t1 = OrderSend(Symbol(), OP_BUY, lots, NormalizeDouble(Ask, digits), Slippage,
                         sl, tp, "donchian_breakout_EURUSD_H1", MagicNumber, 0, clrDodgerBlue);
      if(t1 < 0) Print("Buy failed err=", GetLastError());
     }
   else
     {
      double sl = NormalizeDouble(Bid + stopDist, digits);
      double tp = NormalizeDouble(Bid - stopDist * RewardRatio, digits);
      int t2 = OrderSend(Symbol(), OP_SELL, lots, NormalizeDouble(Bid, digits), Slippage,
                         sl, tp, "donchian_breakout_EURUSD_H1", MagicNumber, 0, clrOrangeRed);
      if(t2 < 0) Print("Sell failed err=", GetLastError());
     }
  }
