//+------------------------------------------------------------------+
//| donchian_breakout_EURUSD_H1.mq5
//| Generated by the Agentic Trading Firm - Strategy Lab
//| 2026-08-13 04:22 UTC
//|
//| Strategy   : donchian_breakout
//| Symbol/TF  : EURUSD H1
//| Parameters : {"channel": 15, "atr_mult": 1.5, "rr": 4, "buffer_atr": 0}
//|
//| BACKTEST (in-sample, spread-adjusted)
//|   trades 59 | win 38.98% | PF 2.5
//|   expectancy 0.9259R | maxDD 3.036R
//|   sharpe 2.934 | robustness score 1.3935
//| WALK-FORWARD: {"folds": 3, "oos_total_r": 15.196, "oos_trades": 40, "oos_expectancy_r": 0.3799, "params_per_fold": [{"channel": 10, "atr_mult": 1.5, "rr": 2.5, "buf
//|
//| Past performance does not predict future results. Test on demo first.
//+------------------------------------------------------------------+
#property copyright "Agentic Trading Firm"
#property version   "1.00"
#property strict

input double RiskPercent   = 0.75;    // % equity risked per trade
input double ATRMultiplier = 1.5;   // stop distance
input double RewardRatio   = 4.0;   // target = R x stop
input int    ATRPeriod     = 14;
input int    MagicNumber   = 617002;
input int    Slippage      = 20;
input int    MaxPositions  = 1;
input bool   TradeOnNewBarOnly = true;

#include <Trade/Trade.mqh>
CTrade trade;
int atrHandle, fastHandle, slowHandle, rsiHandle, macdHandle, bandsHandle, biasHandle;
datetime lastBar = 0;

int OnInit()
  {
   trade.SetExpertMagicNumber(MagicNumber);
   trade.SetDeviationInPoints(Slippage);
   atrHandle   = iATR(_Symbol, PERIOD_CURRENT, ATRPeriod);
   fastHandle  = iMA(_Symbol, PERIOD_CURRENT, 21, 0, MODE_EMA, PRICE_CLOSE);
   slowHandle  = iMA(_Symbol, PERIOD_CURRENT, 55, 0, MODE_EMA, PRICE_CLOSE);
   biasHandle  = iMA(_Symbol, PERIOD_CURRENT, 100, 0, MODE_EMA, PRICE_CLOSE);
   rsiHandle   = iRSI(_Symbol, PERIOD_CURRENT, 14, PRICE_CLOSE);
   macdHandle  = iMACD(_Symbol, PERIOD_CURRENT, 12, 26, 9, PRICE_CLOSE);
   bandsHandle = iBands(_Symbol, PERIOD_CURRENT, 20, 0, 2.2, PRICE_CLOSE);
   if(atrHandle == INVALID_HANDLE) return INIT_FAILED;
   Print("donchian_breakout_EURUSD_H1 initialised. Risk ", RiskPercent, "% | ATRx", ATRMultiplier, " | RR ", RewardRatio);
   return INIT_SUCCEEDED;
  }

double Buf(int handle, int buffer, int shift)
  {
   double v[];
   if(CopyBuffer(handle, buffer, shift, 1, v) < 1) return 0.0;
   return v[0];
  }
double SlowPrev()      { return Buf(slowHandle, 0, 9); }
double BandLower()     { return Buf(bandsHandle, 2, 1); }
double MacdSignal()    { return Buf(macdHandle, 1, 1); }
double MacdMainPrev()  { return Buf(macdHandle, 0, 2); }
double MacdSignalPrev(){ return Buf(macdHandle, 1, 2); }

void ChannelHL(int n, double &hh, double &ll)
  {
   double h[], l[];
   if(CopyHigh(_Symbol, PERIOD_CURRENT, 2, n, h) < n) { hh = 0; ll = 0; return; }
   if(CopyLow(_Symbol, PERIOD_CURRENT, 2, n, l) < n)  { hh = 0; ll = 0; return; }
   hh = h[ArrayMaximum(h)];
   ll = l[ArrayMinimum(l)];
  }

int CountPositions()
  {
   int c = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong tk = PositionGetTicket(i);
      if(tk == 0) continue;
      if(PositionSelectByTicket(tk) && PositionGetString(POSITION_SYMBOL) == _Symbol
         && PositionGetInteger(POSITION_MAGIC) == MagicNumber) c++;
     }
   return c;
  }

double LotsForRisk(double stopDistance)
  {
   double eq   = AccountInfoDouble(ACCOUNT_EQUITY);
   double risk = eq * RiskPercent / 100.0;
   double tv   = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double ts   = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(ts <= 0 || tv <= 0 || stopDistance <= 0) return 0.0;
   double lossPerLot = stopDistance / ts * tv;
   if(lossPerLot <= 0) return 0.0;
   double lots = risk / lossPerLot;
   double step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double vmin = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double vmax = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   if(step > 0) lots = MathFloor(lots / step) * step;
   if(lots < vmin) return 0.0;
   return MathMin(lots, vmax);
  }

void OnTick()
  {
   if(TradeOnNewBarOnly)
     {
      datetime t = iTime(_Symbol, PERIOD_CURRENT, 0);
      if(t == lastBar) return;
      lastBar = t;
     }
   if(CountPositions() >= MaxPositions) return;

   double atr = Buf(atrHandle, 0, 1);
   if(atr <= 0) return;
   double price = iClose(_Symbol, PERIOD_CURRENT, 1);
   bool buy = false, sell = false;

   double hh = 0, ll = 0;
   ChannelHL(15, hh, ll);
   double buf = atr * 0.0;
   buy  = price > hh + buf;
   sell = price < ll - buf;
   if(!buy && !sell) return;

   double stopDist = atr * ATRMultiplier;
   double lots = LotsForRisk(stopDist);
   if(lots <= 0) return;

   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   if(buy)
     {
      double sl = NormalizeDouble(ask - stopDist, digits);
      double tp = NormalizeDouble(ask + stopDist * RewardRatio, digits);
      trade.Buy(lots, _Symbol, ask, sl, tp, "donchian_breakout_EURUSD_H1");
     }
   else
     {
      double sl = NormalizeDouble(bid + stopDist, digits);
      double tp = NormalizeDouble(bid - stopDist * RewardRatio, digits);
      trade.Sell(lots, _Symbol, bid, sl, tp, "donchian_breakout_EURUSD_H1");
     }
  }
